### ISSUE TITLE
getHomeData - keyNotFound

### ISSUE THREAD

**Issue by encisek** [Baza207/NetatmoSwiftSDK#7]
Hey @Baza207 

I have problem with: 
```
NetatmoSecurity.getHomeData { (result) in
            switch result {
            case .success(let model):
                print(model)
            case .failure(let error):
                print(error)
            }
        }
```

`keyNotFound(CodingKeys(stringValue: "is_local", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "body", intValue: nil), CodingKeys(stringValue: "homes", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "cameras", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"is_local\", intValue: nil) (\"is_local\").", underlyingError: nil))`

Is there maybe a solution?
Thanks!

**Comment by Baza207** [comment]
Hey @encisek 

I've tried a few things to narrow this down but can't seem to find where the issue is.

From your reported error the `is_local` field for Camera objects is not returned by Netatmo. However in the latest version of the Develop branch I've made `isLocal` an optional parameter which should solve this issue. For all my cameras that field is always returned, so I'm not sure how much I can test this.

My only suggestion would be to download the project yourself (not with CocoaPods) and try and run the tests. There's a file in documentation on how to setup the tests for the project, along with test parameter data.

If you get that working I'd be interested in if it works in the test or returns the same (or different) error.

Or if it still errors the same, then if you're to check the raw JOSN response for `getHomeData`. Use something like:


```swift
let json = try? JSONSerialization.jsonObject(with: data, options: []) as? [String: Any]
dump(json!)
```

Put that above line 78 in Source/Manager/NetatmoSecurity.swift.

The response will most likely be quite big, but that'll let us know the actual response from your setup.

Please note, if you post any of it here, please make sure you redact any personal information you don't want to be seen publicly.

I hope this helps. 😄

**Comment by Baza207** [comment]
@encisek Let me know if this issues is still occurring for you, otherwise I'll mark it a closed. 🙂

**Comment by Baza207** [comment]
Closing due to lack of information to reproduce
